[pytest]
addopts = --cov-report term-missing --cov=app --cov=tests/ --cov-config=.coveragerc
filterwarnings = ignore::DeprecationWarning

[behave]
paths = tests/bdd/features/
steps-directory = tests/bdd/features/steps
