name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lint code with pylint
      run: |
        source venv/bin/activate
        pylint app.py tests/

    - name: Run tests with pytest
      run: |
        source venv/bin/activate
        pytest --cov=app --cov=tests --cov-report=term
